### ISSUE TITLE
Giant Hitbox bug

### ISSUE THREAD

**Issue by Gametunes** [Fi0x/DeepMagic#34]
**Describe the bug**
The Hitbox of the giant is only working in the lower 4 blocks, not above

**To Reproduce**
1. Hit
2. ...
3. Profit

**Expected behavior**
Hitting the model also hits the Giant

**Screenshots**
pew pew

**Additional context**
The problem is usually in front of the screen

**Comment by Fi0x** [comment]
I'm currently working on a new model for the giant that shouldn't have this problem

**Comment by Fi0x** [comment]
Fixed the bug
