### ISSUE TITLE
Plasma Guns (Chargeable Spells)

### ISSUE THREAD

**Issue by BunnymcMuffins** [Fi0x/DeepMagic#90]
**Describe the feature you'd like**
Try to describe the feature as precise as possible
I was reading up on the mod and saw you wanted to add reusable scrolls and i wanted to make some sort of super charged scroll/plasma gun (preferably one that's solar powered or doesn't need ammo, something like that)
**Describe alternatives you've considered**
If the request requires too much time to develop, you can write here a description of functions that are not essential to you.
Something with a plasma gun lol
**Additional context**
The coolest art I've seen for a magic is this magic barrier kind of thing https://www.youtube.com/watch?v=Bd-ww-BDQMA&feature=youtu.be

**Comment by Fi0x** [comment]
Do you mean by plasma gun something like the last item that is used in the video?

**Comment by Fi0x** [comment]
I'm currently working on an annihilation spell, that kills every mob in an AOE around the impact point.
- This won't do any environmental damage
- It will do a lot of damage to each single mob that is within the area (at least 10-20 Hearts)
- I might include a variant that has the caster as origin point

**Comment by BunnymcMuffins** [comment]
I'd prefer a beam /bolt kind of spell preferably like a plasma gun that can be fired rapidly through the use the use of overcharging a scroll with a device, creating that kind of rapid fire bolt / beam kind of attack. Sorry for the confusion I just like that general art where it can even look like a charge up. Its a really specific so if something like that would be a bit difficult to code take my suggestion with a grain of salt. You already sound like you're making great stuff

**Comment by Fi0x** [comment]
So if I understand you correctly, you would like **a spell**, that can be **charged / loaded** with a magic item or block and then **fired as rapidly as a gun**.

Did I understand you correctly?

Would the effect of the spell be important for you or would you just like to see this kind of spellcasting in the mod?

**Comment by BunnymcMuffins** [comment]
The effect doesn't matter but I'd like to see that kind of thing in a magic mod

**Comment by Fi0x** [comment]
Ok, thank you.

I'll try to implement that.

**Comment by Fi0x** [comment]
## Added Chargeable Spells
**Working on Charging mechanism**

**Comment by Fi0x** [comment]
# Added Mana altar which can charge the spells
